services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: job-finder-react:latest
    container_name: job-finder-ui
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    external: true
    name: job-finder-backend-node_job-network
